name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Build
      run: dotnet build -c Release

    - name: Publish Artifacts
      run: dotnet publish -c Release -o out

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifacts
        path: out
